### ISSUE TITLE
some requests

### ISSUE THREAD

**Issue by kevdel** [colinl/node-red-contrib-influxdb-backup#2]
#1 have a folder template for where files get saved to so that each backup is stored in its own directory..
set folder = /media/USB/{day.month.year}/

#2 compress the files after backup is complete

**Comment by colinl** [comment]
#1.
The principle reason for developing the node was to allow incremental backups, so that the backup only includes differences between backup versions.  Therefore the ability to save to different directories has no value for me personally.  In addition there seems little point in doing additional work on a node for influxdb 1.8 as it has been superceeded by v2.  However I would be open to merging a Pull Request to add the feature if someone provided it.

#2
There is already and option to specifiy that that the files are left compressed, so I don't see the point in re-compressing them.
